CREATE TABLE MON_UTILISATEUR (ID BIGINT AUTO_INCREMENT PRIMARY KEY, LOGIN VARCHAR, MOT_DE_PASSE VARCHAR);
CREATE TABLE MON_ROLE (ID BIGINT AUTO_INCREMENT PRIMARY KEY, NOM VARCHAR);
CREATE TABLE MA_PERMISSION (ID BIGINT AUTO_INCREMENT PRIMARY KEY, NOM VARCHAR);

CREATE TABLE UTILISATEUR_ROLE (UTILISATEUR_ID BIGINT, 
								ROLE_ID BIGINT, 
								CONSTRAINT PK_UTILISATEUR_ROLE_ID
							        PRIMARY KEY (UTILISATEUR_ID, ROLE_ID),
							    CONSTRAINT FK_UTILISATEUR_ROLE_REF_UTILISATEUR FOREIGN KEY (UTILISATEUR_ID)
							        REFERENCES MON_UTILISATEUR(ID),
						        CONSTRAINT FK_UTILISATEUR_ROLE_REF_ROLE FOREIGN KEY (ROLE_ID)
							        REFERENCES MON_ROLE(ID));
							        
CREATE TABLE ROLE_PERMISSION (ROLE_ID BIGINT, 
								PERMISSION_ID BIGINT, 
								CONSTRAINT PK_ROLE_PERMISSION_ID
							        PRIMARY KEY (ROLE_ID, PERMISSION_ID),
							    CONSTRAINT FK_ROLE_PERMISSION_REF_PERMISSION FOREIGN KEY (PERMISSION_ID)
							        REFERENCES MA_PERMISSION(ID),
						        CONSTRAINT FK_ROLE_PERMISSION_REF_ROLE FOREIGN KEY (ROLE_ID)
							        REFERENCES MON_ROLE(ID));
							        
CREATE TABLE BOOKING (ID BIGINT AUTO_INCREMENT PRIMARY KEY, NOM VARCHAR);
			
--Encodage BCrypt(10) de password
INSERT INTO MON_UTILISATEUR (LOGIN, MOT_DE_PASSE) VALUES ('user', '$2a$10$NL.xWeQJnyZmAx8/InJHa.4LeuOJpNB5gLPUrSLAbHt4RNX/DjJJa'); 
--Encodage BCrypt(10) de admin
INSERT INTO MON_UTILISATEUR (LOGIN, MOT_DE_PASSE) VALUES ('admin', '$2a$10$raaAuA2glwv4IpFfpgBg8eezsZGxHwHgPjKuRAP5g8ruPL7lsZwey');
--Encodage BCrypt(10) de webServicePassword
INSERT INTO MON_UTILISATEUR (LOGIN, MOT_DE_PASSE) VALUES ('webservice', '$2a$10$w0gWeF9BLnhbsCLDjmkTleILSQfXE5jiGL7W0mrzhxSqAGTupopUK');

INSERT INTO MON_ROLE (NOM) VALUES ('ROLE_USER');
INSERT INTO MON_ROLE (NOM) VALUES ('ROLE_ADMIN');


INSERT INTO UTILISATEUR_ROLE(UTILISATEUR_ID, ROLE_ID) 
SELECT DISTINCT U.ID, R.ID
FROM MON_UTILISATEUR U , MON_ROLE R
WHERE U.LOGIN = 'user' AND R.NOM = 'ROLE_USER';

INSERT INTO UTILISATEUR_ROLE(UTILISATEUR_ID, ROLE_ID) 
SELECT DISTINCT U.ID, R.ID
FROM MON_UTILISATEUR U , MON_ROLE R
WHERE U.LOGIN = 'admin' AND R.NOM = 'ROLE_ADMIN';

INSERT INTO UTILISATEUR_ROLE(UTILISATEUR_ID, ROLE_ID) 
SELECT DISTINCT U.ID, R.ID
FROM MON_UTILISATEUR U , MON_ROLE R
WHERE U.LOGIN = 'webservice' AND R.NOM = 'ROLE_USER';

INSERT INTO MA_PERMISSION (NOM) VALUES ('CREATE_BOOKING');
INSERT INTO MA_PERMISSION (NOM) VALUES ('READ_BOOKING');

INSERT INTO ROLE_PERMISSION(ROLE_ID, PERMISSION_ID) 
SELECT DISTINCT R.ID, P.ID
FROM  MON_ROLE R, MA_PERMISSION P
WHERE R.NOM = 'ROLE_ADMIN' AND P.NOM IN ('CREATE_BOOKING', 'READ_BOOKING');

INSERT INTO ROLE_PERMISSION(ROLE_ID, PERMISSION_ID) 
SELECT DISTINCT R.ID, P.ID
FROM  MON_ROLE R, MA_PERMISSION P
WHERE R.NOM = 'ROLE_USER' AND P.NOM IN ( 'READ_BOOKING');

INSERT INTO BOOKING(NOM) VALUES ('Réservation aux Maldives');
INSERT INTO BOOKING(NOM) VALUES ('Réservation en Nouvelle-Zélande');
INSERT INTO BOOKING(NOM) VALUES ('Réservation à Maubeuge');